import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Navigator from "@/components/Navigators";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="flex justify-between bg-white text-black p-4">
          <div className="flex gap-4">
            <Image src="/logo.png" alt="logo" width={32} height={32} />
            <h1 className="font-bold text-2xl">Mugathman Motors</h1>
          </div>
          <Navigator />
        </header>
        {children}
      </body>
    </html>
  );
}
