import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navigator from "@/components/Navigators";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  openGraph: {
    title: "Mugathman Motors - Home",
    description: "Mugathman motors offered a wide range of vehicles including trucks, cars, farm tractors and quality spare parts to meet all your logistics and transportation needs.",
    url: "https://mugathmanmotors.com/",
    siteName: "Mugathman Motors",
    images: [
      {
        url: "/hero.png",
        width: 800,
        height: 600,
      },
    ],
    locale: "en_US",
    type: "website",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="flex justify-between bg-white text-black p-4">
          <div className="flex gap-4">
            <Image src="/logo.png" alt="logo" width={32} height={32} />
            <h1 className="font-bold text-lg md:text-2xl">Mugathman Motors</h1>
          </div>
          <Navigator responsive={true} />
        </header>
        {children}
      </body>
    </html>
  );
}
